#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3

import sys

src = open(sys.argv[1], 'r+t').read()

VERBOSE = 0

def verbose(info):
	if VERBOSE:
		print (info)

def argParse(line):
	if line.strip() == "":
		return []

	k = []
	inQuotes = 0
	acc = ""
	for i in line:
		if i=='"':
			inQuotes = ~inQuotes
		if ~inQuotes and i==" ":
			k.append(acc)
			acc = ""
		else:
			acc += i
	k.append(acc)

	return k

def eval(line, src, scopeNames, scopeValues):
	verbose('eval {} with scope {} : {}'.format(line, scopeNames, scopeValues))

	if line[0]=='[':
		k = []
		for i in argParse(line[1:-1].replace(', ', ' ').replace(',', ' ')):
			k.append(eval(i, src, scopeNames, scopeValues))
		return k

	if line[0]=='"':
		k = []
		for i in line[1:-1]:
			k.append(ord(i))
		return k

	if line[0] in "-.0123456789":
		if '.' in line:
			return float(line)
		else:
			return int(line)

	if line in scopeNames:
		return scopeValues[scopeNames.index(line)]

	tokens = argParse(line)
	name = tokens[0]
	args = tokens[1:]

	# builtins
	if name == "print":
		print(''.join([chr(x) for x in eval(args[0], src, scopeNames, scopeValues)])) # process string literal or vars
		return;
	elif name == "get":
		return eval(args[0], src, scopeNames, scopeValues)[eval(args[1], src, scopeNames, scopeValues)]
	elif name == "add":
		return eval(args[0], src, scopeNames, scopeValues).append(eval(args[1], src, scopeNames, scopeValues))
	elif name == "sum":
		return sum([eval(arg, src, scopeNames, scopeValues) for arg in args])
	elif name == "len":
		return len(eval(args[0], src, scopeNames, scopeValues))
	# user defined
	else:
		verbose ('user func {}'.format(name))
		exec(src, name, [eval(arg, src, scopeNames, scopeValues) for arg in args])

def exec(src, func, args):

	verbose('exec {} with args {}'.format(func, args))

	currLine = 0

	srcArr = src.split('\n')

	for line in srcArr:
		tokens = argParse(line)
		if len(tokens)==0:
			pass
		elif tokens[0] == func and tokens[-1] == ":":
			break
		currLine += 1

	if currLine == len(srcArr):
		raise NameError("Symbol {} is not defined.".format(func))

	for i in range(currLine, len(srcArr)):
		tokens = argParse(srcArr[i])
		if len(tokens)==0:
			pass
		elif tokens[0] == "ret":
			break

	retLoc =  i

	tokens = argParse(srcArr[currLine])
	verbose ('function header {}'.format(srcArr[currLine]))
	verbose ('arg tokens {}'.format(tokens[1:-1]))

	#TODO: arg and local scope don't need to be seperate

	argNames = tokens[1:-1]
	argValues = args

	localNames = []
	localValues = []


	# step
	while currLine < retLoc:
		currLine += 1

		tokens = argParse(srcArr[currLine])

		# no execute
		if len(tokens) == 0 or tokens[0]=="%" or tokens[-1]==":":
			continue

		# assignment
		elif len(tokens) >= 2 and tokens[1] == "=":
			name = tokens[0].strip()
			value = ' '.join(tokens[2:])
			if name in localNames:
				localValues[localNames.index(name)] = eval(value, src, argNames+localNames, argValues+localValues)
			else:
				verbose('initializing {}'.format(name))
				verbose('scope {}'.format(argNames))
				localValues.append(eval(value, src, argNames+localNames, argValues+localValues))
				localNames.append(name)

		# returns
		elif tokens[0] == "ret":
			verbose('returning {}'.format(tokens[1:]))
			if len(tokens) == 1:
				return None
			else:
				return eval(tokens[1], src, argNames+localNames, argValues+localValues)

		# control structures
		elif tokens[0] == "ifEq":
			args = tokens[1:]

			if len(args) == 2:
				dest = "end"
			else:
				dest = args[2]
			if (dest=="end") ^ (eval(args[0], src, argNames+localNames, argValues+localValues) == eval(args[1], src, argNames+localNames, argValues+localValues)):
				while argParse(srcArr[currLine])[0] != dest:
					currLine += -1 if dest=="while" else 1

		elif tokens[0] == "ifLess":
			args = tokens[1:]

			if len(args) == 2:
				dest = "end"
			else:
				dest = args[2]
			if (dest=="end") ^ (eval(args[0], src, argNames+localNames, argValues+localValues) < eval(args[1], src, argNames+localNames, argValues+localValues)):
				while argParse(srcArr[currLine])[0] != dest:
					currLine += -1 if dest=="while" else 1

		else: # arbitrary function call
			verbose("root function call {{{}}}".format(srcArr[currLine]))
			eval(srcArr[currLine], src, argNames+localNames, argValues+localValues)

exec(src, "main", [])